2021/02/20 11:35:06 Ass_main.py[line:68] INFO ######## Tools start ########
2021/02/20 11:35:06 Ass_main.py[line:165] INFO ######>>> Check device
2021/02/20 11:35:06 Ass_main.py[line:180] DEBUG Device list:[]
2021/02/20 11:35:06 Ass_main.py[line:432] INFO ######>>> Check port
2021/02/20 11:35:06 Ass_main.py[line:440] DEBUG Port list:{'COM1': '通信端口 (COM1)', 'COM3': 'LeadCore CMCC Diagnoses (COM3)', 'COM8': 'LeadCore CMCC AT Interface (COM8)'}
2021/02/20 11:35:06 Ass_main.py[line:915] INFO ######>>> Init settings AT Dialog
2021/02/20 11:35:06 Ass_main.py[line:982] INFO ######>>> Init Default settings Dialog
2021/02/20 11:35:11 Ass_main.py[line:446] INFO ######>>> Open port
2021/02/20 11:35:11 Ass_main.py[line:449] INFO Port:COM8  baudrate:115200  bytesize:8  parity:N  stopbits:1
2021/02/20 11:35:11 Ass_main.py[line:537] DEBUG Receive data:
^SATSIGNAL:-109,91

^CPSTATE: -109,381,37,84

2021/02/20 11:35:14 Ass_main.py[line:694] DEBUG calling_to_answer
2021/02/20 11:35:14 Ass_main.py[line:720] DEBUG test times:3
2021/02/20 11:35:16 Ass_main.py[line:465] INFO ######>>> Close port
2021/02/20 11:35:16 Ass_main.py[line:586] WARNING Attempting to use a port that is not open
2021/02/20 11:35:16 Ass_main.py[line:729] INFO 主叫接听 >> 第1次, 共3次,
2021/02/20 11:35:19 Ass_main.py[line:735] DEBUG dial process: []
2021/02/20 11:35:19 Ass_main.py[line:747] ERROR 拨打失败，请检查设备是否入网
2021/02/20 11:35:19 Ass_main.py[line:760] INFO 测试项：主叫接听 测试次数:1, pass:0, fail:1

2021/02/20 11:37:29 Ass_main.py[line:432] INFO ######>>> Check port
2021/02/20 11:37:29 Ass_main.py[line:440] DEBUG Port list:{'COM1': '通信端口 (COM1)', 'COM3': 'LeadCore CMCC Diagnoses (COM3)', 'COM8': 'LeadCore CMCC AT Interface (COM8)'}
2021/02/20 11:37:29 Ass_main.py[line:432] INFO ######>>> Check port
2021/02/20 11:37:29 Ass_main.py[line:440] DEBUG Port list:{'COM1': '通信端口 (COM1)', 'COM3': 'LeadCore CMCC Diagnoses (COM3)', 'COM8': 'LeadCore CMCC AT Interface (COM8)'}
2021/02/20 11:37:29 Ass_main.py[line:432] INFO ######>>> Check port
2021/02/20 11:37:29 Ass_main.py[line:440] DEBUG Port list:{'COM1': '通信端口 (COM1)', 'COM3': 'LeadCore CMCC Diagnoses (COM3)', 'COM8': 'LeadCore CMCC AT Interface (COM8)'}
2021/02/20 11:37:30 Ass_main.py[line:432] INFO ######>>> Check port
2021/02/20 11:37:30 Ass_main.py[line:440] DEBUG Port list:{'COM1': '通信端口 (COM1)', 'COM3': 'LeadCore CMCC Diagnoses (COM3)', 'COM8': 'LeadCore CMCC AT Interface (COM8)'}
2021/02/20 11:37:30 Ass_main.py[line:432] INFO ######>>> Check port
2021/02/20 11:37:30 Ass_main.py[line:440] DEBUG Port list:{'COM1': '通信端口 (COM1)', 'COM3': 'LeadCore CMCC Diagnoses (COM3)', 'COM8': 'LeadCore CMCC AT Interface (COM8)'}
2021/02/20 11:37:33 Ass_main.py[line:432] INFO ######>>> Check port
2021/02/20 11:37:33 Ass_main.py[line:440] DEBUG Port list:{'COM1': '通信端口 (COM1)', 'COM3': 'LeadCore CMCC Diagnoses (COM3)', 'COM8': 'LeadCore CMCC AT Interface (COM8)'}
2021/02/20 11:37:33 Ass_main.py[line:432] INFO ######>>> Check port
2021/02/20 11:37:33 Ass_main.py[line:440] DEBUG Port list:{'COM1': '通信端口 (COM1)', 'COM3': 'LeadCore CMCC Diagnoses (COM3)', 'COM8': 'LeadCore CMCC AT Interface (COM8)'}
2021/02/20 11:37:33 Ass_main.py[line:432] INFO ######>>> Check port
2021/02/20 11:37:33 Ass_main.py[line:440] DEBUG Port list:{'COM1': '通信端口 (COM1)', 'COM3': 'LeadCore CMCC Diagnoses (COM3)', 'COM8': 'LeadCore CMCC AT Interface (COM8)'}
2021/02/20 11:37:34 Ass_main.py[line:432] INFO ######>>> Check port
2021/02/20 11:37:34 Ass_main.py[line:440] DEBUG Port list:{'COM1': '通信端口 (COM1)', 'COM3': 'LeadCore CMCC Diagnoses (COM3)', 'COM8': 'LeadCore CMCC AT Interface (COM8)'}
2021/02/20 11:37:39 Ass_main.py[line:446] INFO ######>>> Open port
2021/02/20 11:37:39 Ass_main.py[line:449] INFO Port:COM8  baudrate:115200  bytesize:8  parity:N  stopbits:1
2021/02/20 11:37:46 Ass_main.py[line:499] INFO Send choose at  ./:AT+CFUN?
2021/02/20 11:37:46 Ass_main.py[line:537] DEBUG Receive data:
+CFUN: 1

OK

2021/02/20 11:37:48 Ass_main.py[line:499] INFO Send choose at  ./:AT^DGSN?
2021/02/20 11:37:48 Ass_main.py[line:537] DEBUG Receive data:
^DGSN: 860106000336556

OK

2021/02/20 11:37:51 Ass_main.py[line:499] INFO Send choose at  ./:AT^DMSN
2021/02/20 11:37:51 Ass_main.py[line:537] DEBUG Receive data:
^DMSN: 

OK

2021/02/20 11:37:53 Ass_main.py[line:537] DEBUG Receive data:
^DGSQU: 31,3

+CSQ: 31,3

2021/02/20 11:37:53 Ass_main.py[line:537] DEBUG Receive data:
^SATSIGNAL:-108,86

^CPSTATE: -108,381,37,84

2021/02/20 11:37:54 Ass_main.py[line:499] INFO Send choose at  ./:AT+CGMR
2021/02/20 11:37:54 Ass_main.py[line:537] DEBUG Receive data:
+CGMR: HL1.30.20,PL








OK

2021/02/20 11:37:58 Ass_main.py[line:499] INFO Send choose at  ./:AT+CGMR
2021/02/20 11:37:58 Ass_main.py[line:537] DEBUG Receive data:
+CGMR: HL1.30.20,PL







2021/02/20 11:37:58 Ass_main.py[line:537] DEBUG Receive data:

OK

2021/02/20 11:38:03 Ass_main.py[line:499] INFO Send choose at  ./:AT+CHUP
2021/02/20 11:38:03 Ass_main.py[line:537] DEBUG Receive data:
OK

2021/02/20 11:38:07 Ass_main.py[line:698] DEBUG caller_hangs_up
2021/02/20 11:38:07 Ass_main.py[line:771] DEBUG test times:3
2021/02/20 11:38:09 Ass_main.py[line:499] INFO Send choose at  ./:AT+CHUP
2021/02/20 11:38:09 Ass_main.py[line:537] DEBUG Receive data:
OK

2021/02/20 11:38:09 Ass_main.py[line:584] INFO exec >> ATD18701997306;
2021/02/20 11:38:09 Ass_main.py[line:779] INFO 主叫挂断 >> 第1次, 共3次,
2021/02/20 11:38:09 Ass_main.py[line:537] DEBUG Receive data:
OK

2021/02/20 11:38:09 Ass_main.py[line:537] DEBUG Receive data:
NO CARRIER

2021/02/20 11:38:12 Ass_main.py[line:785] DEBUG dial process: []
2021/02/20 11:38:12 Ass_main.py[line:797] ERROR 拨打失败，请检查是被是否入网
2021/02/20 11:38:12 Ass_main.py[line:808] INFO 测试项：主叫接听 测试次数:1, pass:0, fail:1

2021/02/20 11:38:12 Ass_main.py[line:499] INFO Send choose at  ./:AT
2021/02/20 11:38:13 Ass_main.py[line:537] DEBUG Receive data:
OK

2021/02/20 11:38:24 Ass_main.py[line:537] DEBUG Receive data:
^DGSQU: 14,1

+CSQ: 14,1

2021/02/20 11:38:24 Ass_main.py[line:537] DEBUG Receive data:
^SATSIGNAL:-125,56

^CPSTATE: -125,381,37,84

2021/02/20 11:38:35 Ass_main.py[line:694] DEBUG calling_to_answer
2021/02/20 11:38:35 Ass_main.py[line:720] DEBUG test times:3
2021/02/20 11:38:37 Ass_main.py[line:584] INFO exec >> ATD18701997306;
2021/02/20 11:38:37 Ass_main.py[line:729] INFO 主叫接听 >> 第1次, 共3次,
2021/02/20 11:38:37 Ass_main.py[line:537] DEBUG Receive data:
OK

NO CARRIER

2021/02/20 11:38:37 Ass_main.py[line:537] DEBUG Receive data:
^SATSIGNAL:-108,82

^CPSTATE: -108,381,37,84

2021/02/20 11:38:40 Ass_main.py[line:735] DEBUG dial process: []
2021/02/20 11:38:40 Ass_main.py[line:747] ERROR 拨打失败，请检查设备是否入网
2021/02/20 11:38:40 Ass_main.py[line:760] INFO 测试项：主叫接听 测试次数:1, pass:0, fail:1

2021/02/20 11:38:45 Ass_main.py[line:698] DEBUG caller_hangs_up
2021/02/20 11:38:45 Ass_main.py[line:771] DEBUG test times:3
2021/02/20 11:38:47 Ass_main.py[line:584] INFO exec >> ATD18701997306;
2021/02/20 11:38:47 Ass_main.py[line:779] INFO 主叫挂断 >> 第1次, 共3次,
2021/02/20 11:38:47 Ass_main.py[line:537] DEBUG Receive data:
OK

NO CARRIER

2021/02/20 11:38:50 Ass_main.py[line:785] DEBUG dial process: []
2021/02/20 11:38:50 Ass_main.py[line:797] ERROR 拨打失败，请检查是被是否入网
2021/02/20 11:38:50 Ass_main.py[line:808] INFO 测试项：主叫接听 测试次数:1, pass:0, fail:1

2021/02/20 11:38:54 Ass_main.py[line:537] DEBUG Receive data:
^DGSQU: 14,1

+CSQ: 14,1

2021/02/20 11:38:54 Ass_main.py[line:537] DEBUG Receive data:
^SATSIGNAL:-125,47

^CPSTATE: -125,381,37,84

2021/02/20 11:38:58 Ass_main.py[line:702] DEBUG calling_reject
2021/02/20 11:38:58 Ass_main.py[line:819] DEBUG test times:3
2021/02/20 11:39:00 Ass_main.py[line:584] INFO exec >> ATD18701997306;
2021/02/20 11:39:00 Ass_main.py[line:827] INFO 主叫拒接 >> 第1次, 共3次,
2021/02/20 11:39:00 Ass_main.py[line:537] DEBUG Receive data:
OK

NO CARRIER

2021/02/20 11:39:00 Ass_main.py[line:537] DEBUG Receive data:
^SATSIGNAL:-107,82

^CPSTATE: -107,381,37,84

2021/02/20 11:39:03 Ass_main.py[line:832] DEBUG dial process: []
2021/02/20 11:39:03 Ass_main.py[line:842] ERROR 拨打失败，请检查是被是否入网
2021/02/20 11:39:03 Ass_main.py[line:853] INFO 测试项：主叫拒接 测试次数:1, pass:0, fail:1

2021/02/20 11:39:05 Ass_main.py[line:706] DEBUG no_caller_answer
2021/02/20 11:39:05 Ass_main.py[line:864] DEBUG test times:3
2021/02/20 11:39:07 Ass_main.py[line:584] INFO exec >> ATD18701997306;
2021/02/20 11:39:07 Ass_main.py[line:872] INFO 主叫未接 >> 第1次, 共3次,
2021/02/20 11:39:07 Ass_main.py[line:537] DEBUG Receive data:
OK

NO CARRIER

2021/02/20 11:39:08 Ass_main.py[line:537] DEBUG Receive data:
^SATSIGNAL:-106,85

^CPSTATE: -106,381,37,84

2021/02/20 11:39:10 Ass_main.py[line:877] DEBUG dial process: []
2021/02/20 11:39:10 Ass_main.py[line:889] ERROR 拨打失败，请检查是被是否入网
2021/02/20 11:39:10 Ass_main.py[line:900] INFO 测试项：主叫未接 测试次数:1, pass:0, fail:1

2021/02/20 11:39:25 Ass_main.py[line:537] DEBUG Receive data:
^DGSQU: 31,3

2021/02/20 11:39:25 Ass_main.py[line:537] DEBUG Receive data:
+CSQ: 31,3

^SATSIGNAL:-107,86

^CPSTATE: -107,381,37,84

2021/02/20 11:39:56 Ass_main.py[line:537] DEBUG Receive data:
^DGSQU: 14,1

+CSQ: 14,1

^SATSIGNAL:-125,58

2021/02/20 11:39:56 Ass_main.py[line:537] DEBUG Receive data:
^CPSTATE: -125,381,37,84

2021/02/20 11:40:27 Ass_main.py[line:537] DEBUG Receive data:
^DGSQU: 31,2

+CSQ: 31,2

^SATSIGNAL:-107,71

2021/02/20 11:40:27 Ass_main.py[line:537] DEBUG Receive data:
^CPSTATE: -107,381,37,84

2021/02/20 11:40:57 Ass_main.py[line:537] DEBUG Receive data:
^DGSQU: 31,3

+CSQ: 31,3

^SATSIGNAL:-108,85

2021/02/20 11:40:57 Ass_main.py[line:537] DEBUG Receive data:
^CPSTATE: -108,381,37,84

